from __future__ import annotations

import json

from .models import ScanReport


def render_markdown(report: ScanReport) -> str:
    summary = report.to_dict()["summary"]
    lines = [
        "# Environment variable inventory",
        "",
        f"Scan root: `{report.root}`",
        "",
        (
            f"Found **{summary['variables']}** variables: "
            f"**{summary['undocumented']}** undocumented, "
            f"**{summary['unused_examples']}** unused example entries, and "
            f"**{summary['dynamic_accesses']}** dynamic accesses requiring review."
        ),
        "",
        "| Variable | Status | Sensitive name | Usage | Example declarations |",
        "| --- | --- | --- | ---: | --- |",
    ]
    for name in sorted(report.variables):
        record = report.variables[name]
        declarations = (
            ", ".join(f"`{value}`" for value in sorted(record.declared_in_examples)) or "none"
        )
        lines.append(
            f"| `{name}` | {record.status} | {'yes' if record.sensitive else 'no'} | "
            f"{len(record.occurrences)} | {declarations} |"
        )
    if report.dynamic_accesses:
        lines.extend(["", "## Dynamic accesses", ""])
        for occurrence in sorted(report.dynamic_accesses):
            lines.append(f"- `{occurrence.path}:{occurrence.line}` - {occurrence.syntax}")
    lines.extend(
        [
            "",
            "## Safety note",
            "",
            "Real `.env` files were excluded. This report inventories names and "
            "locations, not runtime values.",
            "",
        ]
    )
    return "\n".join(lines)


def render_example(report: ScanReport) -> str:
    lines = [
        "# Generated by Environment Variable Documenter.",
        "# Values are intentionally blank; copy to a private .env file and supply them securely.",
        "",
    ]
    for name in sorted(item.name for item in report.variables.values() if item.occurrences):
        record = report.variables[name]
        if record.sensitive:
            lines.append("# Sensitive value: do not commit the populated value.")
        lines.append(f"{name}=")
    return "\n".join(lines) + "\n"


def render_json(report: ScanReport) -> str:
    return json.dumps(report.to_dict(), indent=2, ensure_ascii=False) + "\n"
